--CREATE TABLE contact(
--id INT PRIMARY KEY IDENTITY(1,1),
--nom varchar(50) NOT NULL,
--prenom varchar(50) NOT NULL,
--telephone varchar(10) NOT NULL
--)
--CREATE TABLE email(
--id INT PRIMARY KEY IDENTITY(1,1),
--mail varchar(100) NOT NULL,
--contact_id INT NOT NULL,
--FOREIGN KEY(contact_id) REFERENCES contact(id)
--)